/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Blessing { 'blessing' : BlessingMessage, 'sender' : Principal }
export type BlessingMessage = string;
export type Blob = Uint8Array;
export type Caption = string;
export type Energy = bigint;
export type EnergyReaction = { 'heart' : null } |
  { 'star' : null } |
  { 'angelBadge' : null };
export interface Experience {
  'id' : ExperienceId,
  'media' : Array<ExternalBlob>,
  'user' : Principal,
  'caption' : Caption,
}
export type ExperienceId = bigint;
export type ExternalBlob = Uint8Array;
export interface Manifest {
  'sayComments' : Array<SayComment>,
  'title' : string,
  'ownerId' : Principal,
  'description' : string,
  'isAttained' : boolean,
  'blessings' : Array<Blessing>,
  'boostCount' : bigint,
  'reactions' : Array<Reaction>,
}
export type ManifestId = bigint;
export type ManifestTitle = string;
export interface Profile {
  'bio' : string,
  'gratitudeStars' : bigint,
  'username' : string,
  'totalBoosts' : bigint,
  'gratitudeHearts' : bigint,
  'gratitude' : Energy,
  'wish' : Energy,
  'desire' : Energy,
  'totalBlessings' : bigint,
  'gratitudeAngles' : bigint,
  'mystery' : Energy,
  'manifestPower' : Energy,
  'avatar' : [] | [ExternalBlob],
}
export interface Reaction { 'type' : EnergyReaction, 'sender' : Principal }
export interface SayComment { 'text' : string, 'sender' : Principal }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEnergyGratitude' : ActorMethod<[Principal, EnergyReaction], undefined>,
  'addExperience' : ActorMethod<[Array<Blob>, Caption], ExperienceId>,
  'addSayComment' : ActorMethod<[ManifestId, string], SayComment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'boostUpManifest' : ActorMethod<[ManifestId], undefined>,
  'createManifest' : ActorMethod<[string, string], ManifestId>,
  'deleteExperience' : ActorMethod<[ExperienceId], undefined>,
  'deleteManifest' : ActorMethod<[ManifestId], undefined>,
  'deleteProfile' : ActorMethod<[Principal], undefined>,
  'getAdminManifests' : ActorMethod<[Principal], Array<Manifest>>,
  'getAllManifests' : ActorMethod<[], Array<Manifest>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExperience' : ActorMethod<[ExperienceId], [] | [Experience]>,
  'getManifest' : ActorMethod<[ManifestId], [] | [Manifest]>,
  'getManifestBlessingCount' : ActorMethod<[ManifestId], bigint>,
  'getManifestByOwner' : ActorMethod<[Principal], Array<Manifest>>,
  'getManifestSayComments' : ActorMethod<[ManifestId], Array<SayComment>>,
  'getManifestsByTitle' : ActorMethod<[ManifestTitle], Array<Manifest>>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getTopUsers' : ActorMethod<[bigint], Array<Profile>>,
  'getUserBlessings' : ActorMethod<[Principal], Array<Blessing>>,
  'getUserManifestsSnapshot' : ActorMethod<[Principal], Array<Manifest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markManifestAttained' : ActorMethod<[ManifestId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'saveProfile' : ActorMethod<[Profile], undefined>,
  'sendBlessing' : ActorMethod<[ManifestId, BlessingMessage], Blessing>,
  'sendEnergyReaction' : ActorMethod<[ManifestId, EnergyReaction], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];