/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EnergyReaction = IDL.Variant({
  'heart' : IDL.Null,
  'star' : IDL.Null,
  'angelBadge' : IDL.Null,
});
export const Blob = IDL.Vec(IDL.Nat8);
export const Caption = IDL.Text;
export const ExperienceId = IDL.Nat;
export const ManifestId = IDL.Nat;
export const SayComment = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlessingMessage = IDL.Text;
export const Blessing = IDL.Record({
  'blessing' : BlessingMessage,
  'sender' : IDL.Principal,
});
export const Reaction = IDL.Record({
  'type' : EnergyReaction,
  'sender' : IDL.Principal,
});
export const Manifest = IDL.Record({
  'sayComments' : IDL.Vec(SayComment),
  'title' : IDL.Text,
  'ownerId' : IDL.Principal,
  'description' : IDL.Text,
  'isAttained' : IDL.Bool,
  'blessings' : IDL.Vec(Blessing),
  'boostCount' : IDL.Nat,
  'reactions' : IDL.Vec(Reaction),
});
export const Energy = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'gratitudeStars' : IDL.Nat,
  'username' : IDL.Text,
  'totalBoosts' : IDL.Nat,
  'gratitudeHearts' : IDL.Nat,
  'gratitude' : Energy,
  'wish' : Energy,
  'desire' : Energy,
  'totalBlessings' : IDL.Nat,
  'gratitudeAngles' : IDL.Nat,
  'mystery' : Energy,
  'manifestPower' : Energy,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Experience = IDL.Record({
  'id' : ExperienceId,
  'media' : IDL.Vec(ExternalBlob),
  'user' : IDL.Principal,
  'caption' : Caption,
});
export const ManifestTitle = IDL.Text;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEnergyGratitude' : IDL.Func([IDL.Principal, EnergyReaction], [], []),
  'addExperience' : IDL.Func([IDL.Vec(Blob), Caption], [ExperienceId], []),
  'addSayComment' : IDL.Func([ManifestId, IDL.Text], [SayComment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'boostUpManifest' : IDL.Func([ManifestId], [], []),
  'createManifest' : IDL.Func([IDL.Text, IDL.Text], [ManifestId], []),
  'deleteExperience' : IDL.Func([ExperienceId], [], []),
  'deleteManifest' : IDL.Func([ManifestId], [], []),
  'deleteProfile' : IDL.Func([IDL.Principal], [], []),
  'getAdminManifests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Manifest)],
      ['query'],
    ),
  'getAllManifests' : IDL.Func([], [IDL.Vec(Manifest)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExperience' : IDL.Func([ExperienceId], [IDL.Opt(Experience)], ['query']),
  'getManifest' : IDL.Func([ManifestId], [IDL.Opt(Manifest)], ['query']),
  'getManifestBlessingCount' : IDL.Func([ManifestId], [IDL.Nat], ['query']),
  'getManifestByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Manifest)],
      ['query'],
    ),
  'getManifestSayComments' : IDL.Func(
      [ManifestId],
      [IDL.Vec(SayComment)],
      ['query'],
    ),
  'getManifestsByTitle' : IDL.Func(
      [ManifestTitle],
      [IDL.Vec(Manifest)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], []),
  'getTopUsers' : IDL.Func([IDL.Nat], [IDL.Vec(Profile)], ['query']),
  'getUserBlessings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Blessing)],
      ['query'],
    ),
  'getUserManifestsSnapshot' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Manifest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markManifestAttained' : IDL.Func([ManifestId], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'saveProfile' : IDL.Func([Profile], [], []),
  'sendBlessing' : IDL.Func([ManifestId, BlessingMessage], [Blessing], []),
  'sendEnergyReaction' : IDL.Func([ManifestId, EnergyReaction], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EnergyReaction = IDL.Variant({
    'heart' : IDL.Null,
    'star' : IDL.Null,
    'angelBadge' : IDL.Null,
  });
  const Blob = IDL.Vec(IDL.Nat8);
  const Caption = IDL.Text;
  const ExperienceId = IDL.Nat;
  const ManifestId = IDL.Nat;
  const SayComment = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlessingMessage = IDL.Text;
  const Blessing = IDL.Record({
    'blessing' : BlessingMessage,
    'sender' : IDL.Principal,
  });
  const Reaction = IDL.Record({
    'type' : EnergyReaction,
    'sender' : IDL.Principal,
  });
  const Manifest = IDL.Record({
    'sayComments' : IDL.Vec(SayComment),
    'title' : IDL.Text,
    'ownerId' : IDL.Principal,
    'description' : IDL.Text,
    'isAttained' : IDL.Bool,
    'blessings' : IDL.Vec(Blessing),
    'boostCount' : IDL.Nat,
    'reactions' : IDL.Vec(Reaction),
  });
  const Energy = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'gratitudeStars' : IDL.Nat,
    'username' : IDL.Text,
    'totalBoosts' : IDL.Nat,
    'gratitudeHearts' : IDL.Nat,
    'gratitude' : Energy,
    'wish' : Energy,
    'desire' : Energy,
    'totalBlessings' : IDL.Nat,
    'gratitudeAngles' : IDL.Nat,
    'mystery' : Energy,
    'manifestPower' : Energy,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Experience = IDL.Record({
    'id' : ExperienceId,
    'media' : IDL.Vec(ExternalBlob),
    'user' : IDL.Principal,
    'caption' : Caption,
  });
  const ManifestTitle = IDL.Text;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEnergyGratitude' : IDL.Func([IDL.Principal, EnergyReaction], [], []),
    'addExperience' : IDL.Func([IDL.Vec(Blob), Caption], [ExperienceId], []),
    'addSayComment' : IDL.Func([ManifestId, IDL.Text], [SayComment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'boostUpManifest' : IDL.Func([ManifestId], [], []),
    'createManifest' : IDL.Func([IDL.Text, IDL.Text], [ManifestId], []),
    'deleteExperience' : IDL.Func([ExperienceId], [], []),
    'deleteManifest' : IDL.Func([ManifestId], [], []),
    'deleteProfile' : IDL.Func([IDL.Principal], [], []),
    'getAdminManifests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Manifest)],
        ['query'],
      ),
    'getAllManifests' : IDL.Func([], [IDL.Vec(Manifest)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExperience' : IDL.Func(
        [ExperienceId],
        [IDL.Opt(Experience)],
        ['query'],
      ),
    'getManifest' : IDL.Func([ManifestId], [IDL.Opt(Manifest)], ['query']),
    'getManifestBlessingCount' : IDL.Func([ManifestId], [IDL.Nat], ['query']),
    'getManifestByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Manifest)],
        ['query'],
      ),
    'getManifestSayComments' : IDL.Func(
        [ManifestId],
        [IDL.Vec(SayComment)],
        ['query'],
      ),
    'getManifestsByTitle' : IDL.Func(
        [ManifestTitle],
        [IDL.Vec(Manifest)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], []),
    'getTopUsers' : IDL.Func([IDL.Nat], [IDL.Vec(Profile)], ['query']),
    'getUserBlessings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Blessing)],
        ['query'],
      ),
    'getUserManifestsSnapshot' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Manifest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markManifestAttained' : IDL.Func([ManifestId], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'saveProfile' : IDL.Func([Profile], [], []),
    'sendBlessing' : IDL.Func([ManifestId, BlessingMessage], [Blessing], []),
    'sendEnergyReaction' : IDL.Func([ManifestId, EnergyReaction], [], []),
  });
};

export const init = ({ IDL }) => { return []; };