/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Caption = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type ManifestTitle = string;
export type ManifestId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ExperienceId = bigint;
export interface Profile {
    bio: string;
    gratitudeStars: bigint;
    username: string;
    totalBoosts: bigint;
    gratitudeHearts: bigint;
    gratitude: Energy;
    wish: Energy;
    desire: Energy;
    totalBlessings: bigint;
    gratitudeAngles: bigint;
    mystery: Energy;
    manifestPower: Energy;
    avatar?: ExternalBlob;
}
export type Energy = bigint;
export type Blob = Uint8Array;
export type BlessingMessage = string;
export interface Experience {
    id: ExperienceId;
    media: Array<ExternalBlob>;
    user: Principal;
    caption: Caption;
}
export interface Blessing {
    blessing: BlessingMessage;
    sender: Principal;
}
export interface SayComment {
    text: string;
    sender: Principal;
}
export interface Manifest {
    sayComments: Array<SayComment>;
    title: string;
    ownerId: Principal;
    description: string;
    isAttained: boolean;
    blessings: Array<Blessing>;
    boostCount: bigint;
    reactions: Array<Reaction>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Reaction {
    type: EnergyReaction;
    sender: Principal;
}
export enum EnergyReaction {
    heart = "heart",
    star = "star",
    angelBadge = "angelBadge"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEnergyGratitude(profileId: Principal, energyType: EnergyReaction): Promise<void>;
    addExperience(media: Array<Blob>, caption: Caption): Promise<ExperienceId>;
    addSayComment(manifestId: ManifestId, text: string): Promise<SayComment>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    boostUpManifest(manifestId: ManifestId): Promise<void>;
    createManifest(title: string, description: string): Promise<ManifestId>;
    deleteExperience(experienceId: ExperienceId): Promise<void>;
    deleteManifest(manifestId: ManifestId): Promise<void>;
    deleteProfile(user: Principal): Promise<void>;
    getAdminManifests(admin: Principal): Promise<Array<Manifest>>;
    getAllManifests(): Promise<Array<Manifest>>;
    getAllProfiles(): Promise<Array<Profile>>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExperience(id: ExperienceId): Promise<Experience | null>;
    getManifest(manifestId: ManifestId): Promise<Manifest | null>;
    getManifestBlessingCount(manifestId: ManifestId): Promise<bigint>;
    getManifestByOwner(user: Principal): Promise<Array<Manifest>>;
    getManifestSayComments(manifestId: ManifestId): Promise<Array<SayComment>>;
    getManifestsByTitle(substring: ManifestTitle): Promise<Array<Manifest>>;
    getProfile(user: Principal): Promise<Profile | null>;
    getTopUsers(limit: bigint): Promise<Array<Profile>>;
    getUserBlessings(user: Principal): Promise<Array<Blessing>>;
    getUserManifestsSnapshot(owner: Principal): Promise<Array<Manifest>>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    markManifestAttained(manifestId: ManifestId): Promise<void>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
    saveProfile(profile: Profile): Promise<void>;
    sendBlessing(manifestId: ManifestId, blessing: BlessingMessage): Promise<Blessing>;
    sendEnergyReaction(manifestId: ManifestId, reactionType: EnergyReaction): Promise<void>;
}
import type { Blessing as _Blessing, Caption as _Caption, Energy as _Energy, EnergyReaction as _EnergyReaction, Experience as _Experience, ExperienceId as _ExperienceId, ExternalBlob as _ExternalBlob, Manifest as _Manifest, Profile as _Profile, Reaction as _Reaction, SayComment as _SayComment, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEnergyGratitude(arg0: Principal, arg1: EnergyReaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEnergyGratitude(arg0, to_candid_EnergyReaction_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEnergyGratitude(arg0, to_candid_EnergyReaction_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addExperience(arg0: Array<Blob>, arg1: Caption): Promise<ExperienceId> {
        if (this.processError) {
            try {
                const result = await this.actor.addExperience(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExperience(arg0, arg1);
            return result;
        }
    }
    async addSayComment(arg0: ManifestId, arg1: string): Promise<SayComment> {
        if (this.processError) {
            try {
                const result = await this.actor.addSayComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSayComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async boostUpManifest(arg0: ManifestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.boostUpManifest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.boostUpManifest(arg0);
            return result;
        }
    }
    async createManifest(arg0: string, arg1: string): Promise<ManifestId> {
        if (this.processError) {
            try {
                const result = await this.actor.createManifest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createManifest(arg0, arg1);
            return result;
        }
    }
    async deleteExperience(arg0: ExperienceId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExperience(arg0);
            return result;
        }
    }
    async deleteManifest(arg0: ManifestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteManifest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteManifest(arg0);
            return result;
        }
    }
    async deleteProfile(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProfile(arg0);
            return result;
        }
    }
    async getAdminManifests(arg0: Principal): Promise<Array<Manifest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminManifests(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminManifests(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllManifests(): Promise<Array<Manifest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllManifests();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllManifests();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExperience(arg0: ExperienceId): Promise<Experience | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperience(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperience(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManifest(arg0: ManifestId): Promise<Manifest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getManifest(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManifest(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManifestBlessingCount(arg0: ManifestId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getManifestBlessingCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManifestBlessingCount(arg0);
            return result;
        }
    }
    async getManifestByOwner(arg0: Principal): Promise<Array<Manifest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getManifestByOwner(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManifestByOwner(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getManifestSayComments(arg0: ManifestId): Promise<Array<SayComment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getManifestSayComments(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManifestSayComments(arg0);
            return result;
        }
    }
    async getManifestsByTitle(arg0: ManifestTitle): Promise<Array<Manifest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getManifestsByTitle(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManifestsByTitle(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopUsers(arg0: bigint): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopUsers(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopUsers(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBlessings(arg0: Principal): Promise<Array<Blessing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBlessings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBlessings(arg0);
            return result;
        }
    }
    async getUserManifestsSnapshot(arg0: Principal): Promise<Array<Manifest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserManifestsSnapshot(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserManifestsSnapshot(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markManifestAttained(arg0: ManifestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markManifestAttained(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markManifestAttained(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_Profile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_Profile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(await to_candid_Profile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(await to_candid_Profile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendBlessing(arg0: ManifestId, arg1: BlessingMessage): Promise<Blessing> {
        if (this.processError) {
            try {
                const result = await this.actor.sendBlessing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendBlessing(arg0, arg1);
            return result;
        }
    }
    async sendEnergyReaction(arg0: ManifestId, arg1: EnergyReaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendEnergyReaction(arg0, to_candid_EnergyReaction_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendEnergyReaction(arg0, to_candid_EnergyReaction_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EnergyReaction_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnergyReaction): EnergyReaction {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Experience_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Experience): Promise<Experience> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Manifest_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Manifest): Manifest {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_Profile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Promise<Profile> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Reaction_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reaction): Reaction {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Promise<Profile | null> {
    return value.length === 0 ? null : await from_candid_Profile_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Experience]): Promise<Experience | null> {
    return value.length === 0 ? null : await from_candid_Experience_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Manifest]): Manifest | null {
    return value.length === 0 ? null : from_candid_Manifest_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sayComments: Array<_SayComment>;
    title: string;
    ownerId: Principal;
    description: string;
    isAttained: boolean;
    blessings: Array<_Blessing>;
    boostCount: bigint;
    reactions: Array<_Reaction>;
}): {
    sayComments: Array<SayComment>;
    title: string;
    ownerId: Principal;
    description: string;
    isAttained: boolean;
    blessings: Array<Blessing>;
    boostCount: bigint;
    reactions: Array<Reaction>;
} {
    return {
        sayComments: value.sayComments,
        title: value.title,
        ownerId: value.ownerId,
        description: value.description,
        isAttained: value.isAttained,
        blessings: value.blessings,
        boostCount: value.boostCount,
        reactions: from_candid_vec_n15(_uploadFile, _downloadFile, value.reactions)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    type: _EnergyReaction;
    sender: Principal;
}): {
    type: EnergyReaction;
    sender: Principal;
} {
    return {
        type: from_candid_EnergyReaction_n18(_uploadFile, _downloadFile, value.type),
        sender: value.sender
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    gratitudeStars: bigint;
    username: string;
    totalBoosts: bigint;
    gratitudeHearts: bigint;
    gratitude: _Energy;
    wish: _Energy;
    desire: _Energy;
    totalBlessings: bigint;
    gratitudeAngles: bigint;
    mystery: _Energy;
    manifestPower: _Energy;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    bio: string;
    gratitudeStars: bigint;
    username: string;
    totalBoosts: bigint;
    gratitudeHearts: bigint;
    gratitude: Energy;
    wish: Energy;
    desire: Energy;
    totalBlessings: bigint;
    gratitudeAngles: bigint;
    mystery: Energy;
    manifestPower: Energy;
    avatar?: ExternalBlob;
}> {
    return {
        bio: value.bio,
        gratitudeStars: value.gratitudeStars,
        username: value.username,
        totalBoosts: value.totalBoosts,
        gratitudeHearts: value.gratitudeHearts,
        gratitude: value.gratitude,
        wish: value.wish,
        desire: value.desire,
        totalBlessings: value.totalBlessings,
        gratitudeAngles: value.gratitudeAngles,
        mystery: value.mystery,
        manifestPower: value.manifestPower,
        avatar: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExperienceId;
    media: Array<_ExternalBlob>;
    user: Principal;
    caption: _Caption;
}): Promise<{
    id: ExperienceId;
    media: Array<ExternalBlob>;
    user: Principal;
    caption: Caption;
}> {
    return {
        id: value.id,
        media: await from_candid_vec_n31(_uploadFile, _downloadFile, value.media),
        user: value.user,
        caption: value.caption
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heart: null;
} | {
    star: null;
} | {
    angelBadge: null;
}): EnergyReaction {
    return "heart" in value ? EnergyReaction.heart : "star" in value ? EnergyReaction.star : "angelBadge" in value ? EnergyReaction.angelBadge : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Manifest>): Array<Manifest> {
    return value.map((x)=>from_candid_Manifest_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reaction>): Array<Reaction> {
    return value.map((x)=>from_candid_Reaction_n16(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Promise<Array<Profile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Profile_n21(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, x)));
}
function to_candid_EnergyReaction_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergyReaction): _EnergyReaction {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Profile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): Promise<_Profile> {
    return await to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    gratitudeStars: bigint;
    username: string;
    totalBoosts: bigint;
    gratitudeHearts: bigint;
    gratitude: Energy;
    wish: Energy;
    desire: Energy;
    totalBlessings: bigint;
    gratitudeAngles: bigint;
    mystery: Energy;
    manifestPower: Energy;
    avatar?: ExternalBlob;
}): Promise<{
    bio: string;
    gratitudeStars: bigint;
    username: string;
    totalBoosts: bigint;
    gratitudeHearts: bigint;
    gratitude: _Energy;
    wish: _Energy;
    desire: _Energy;
    totalBlessings: bigint;
    gratitudeAngles: bigint;
    mystery: _Energy;
    manifestPower: _Energy;
    avatar: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio,
        gratitudeStars: value.gratitudeStars,
        username: value.username,
        totalBoosts: value.totalBoosts,
        gratitudeHearts: value.gratitudeHearts,
        gratitude: value.gratitude,
        wish: value.wish,
        desire: value.desire,
        totalBlessings: value.totalBlessings,
        gratitudeAngles: value.gratitudeAngles,
        mystery: value.mystery,
        manifestPower: value.manifestPower,
        avatar: value.avatar ? candid_some(await to_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value.avatar)) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergyReaction): {
    heart: null;
} | {
    star: null;
} | {
    angelBadge: null;
} {
    return value == EnergyReaction.heart ? {
        heart: null
    } : value == EnergyReaction.star ? {
        star: null
    } : value == EnergyReaction.angelBadge ? {
        angelBadge: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
